<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UsernameEmail_identifier</name>
   <tag></tag>
   <elementGuidId>1b5610e1-c005-434b-aa4a-17b96b77b57e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginUsername</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginUsername']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukkan username/email Agan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69054c94-71cc-4bb8-a297-0eec0433f6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginUsername</value>
      <webElementGuid>2b143d2d-bbb1-4122-b5d2-7a98ac2f8d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>identifier</value>
      <webElementGuid>bdb342ee-a06c-453b-915f-23544cdf49ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4cf89ffd-7067-40c0-a89d-0132c8c0c043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan username/email Agan</value>
      <webElementGuid>9a6f38d9-7063-42db-a949-bb4f3217ffce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-full w-full rounded-3 border border-grey-2 p-2 leading-normal shadow-none outline-none focus:outline-none focus:ring-0 dark:border-grey-5 dark:placeholder:text-tertiary-night bg-white text-primary dark:bg-black dark:text-primary-night</value>
      <webElementGuid>2d0f4f04-be12-4eb8-a687-0e2bfb99ce71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginUsername&quot;)</value>
      <webElementGuid>9c20f428-e378-4645-b9d9-d18689aafa25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginUsername']</value>
      <webElementGuid>548571cf-ea59-4d1a-ac2f-5ca91a6c2fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[4]/div/div/div/form/div[2]/div/input</value>
      <webElementGuid>1c47b182-9f8c-418c-b741-709734a7b1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>5465a01d-ed6a-44d4-8d95-52d4f5920258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'loginUsername' and @name = 'identifier' and @type = 'text' and @placeholder = 'Masukkan username/email Agan']</value>
      <webElementGuid>5576c56d-2653-4a7f-ba8d-d853f4ea2692</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
