<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Masuk</name>
   <tag></tag>
   <elementGuidId>a7387fa0-4de0-4c79-adb0-4f923bb91676</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button_button__kLF2Y.button_regular__bDFYL.button_primary__c13Ke</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/div[4]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Masuk&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77476842-3ed9-4c71-875c-612a49c6d98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button_button__kLF2Y button_regular__bDFYL button_primary__c13Ke</value>
      <webElementGuid>b7df5076-c8f8-4b4f-9280-7954f6dfd181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>be5396a7-a05f-433a-9b35-a45b7c5a08f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sticky left-0 top-0 z-50 w-full border-b border-grey-2 bg-white dark:border-grey-6 dark:bg-grey-7&quot;]/div[@class=&quot;mx-auto flex w-full justify-between px-4 pb-2 pt-2 xl:max-w-7xl&quot;]/div[@class=&quot;ml-2 flex flex-grow items-center justify-end&quot;]/div[@class=&quot;lg:ml-2&quot;]/button[@class=&quot;button_button__kLF2Y button_regular__bDFYL button_primary__c13Ke&quot;]</value>
      <webElementGuid>7d13be33-969b-4de1-999e-d5753e8937d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[4]/button</value>
      <webElementGuid>c0713818-2013-4434-9b32-d1b9836d75f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buat Thread'])[1]/following::button[1]</value>
      <webElementGuid>c77343c5-3476-4f19-9580-bf1b94489fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Komunitas Populer'])[1]/following::button[3]</value>
      <webElementGuid>9807253c-02c9-4024-80e7-530b689f7434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOMUNITAS'])[1]/preceding::button[1]</value>
      <webElementGuid>7a18d4bd-4932-4c56-bb70-e6532f90a1dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For you'])[1]/preceding::button[1]</value>
      <webElementGuid>53ec2ea4-cd45-4ae7-8816-aac9ca10e4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masuk']/parent::*</value>
      <webElementGuid>8b2d5d10-4ab1-46d9-a299-6f1af82d6b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>2fd674a9-2910-4bf7-951b-33b996665fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>ba0306f6-196f-419b-ae7c-5500d47ffd50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
