<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UsernameEmail_identifier</name>
   <tag></tag>
   <elementGuidId>15266d94-90a4-4c65-97d9-e0ed604d631a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginUsername</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginUsername']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukkan username/email Agan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc3aa909-3728-4bad-861f-d5b9177d3f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginUsername</value>
      <webElementGuid>c41789fd-9e6c-4fb1-a8a4-01a01ce895f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>identifier</value>
      <webElementGuid>9762eede-13d8-4de1-8584-6e246931a83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>660db7df-8bd4-46d4-8957-7ac304fbe7df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan username/email Agan</value>
      <webElementGuid>2b029305-2872-43ed-945d-483cddc34941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-full w-full rounded-3 border border-grey-2 p-2 leading-normal shadow-none outline-none focus:outline-none focus:ring-0 dark:border-grey-5 dark:placeholder:text-tertiary-night bg-white text-primary dark:bg-black dark:text-primary-night</value>
      <webElementGuid>945547b9-bd84-41d9-983e-c290ce450277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginUsername&quot;)</value>
      <webElementGuid>ef9804ee-7dfb-40d5-8256-20be0e9d3dce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginUsername']</value>
      <webElementGuid>6f0b6795-d588-41d1-a078-4c237a0a7796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[4]/div/div/div/form/div[2]/div/input</value>
      <webElementGuid>9dafdeb3-e177-46cc-960c-b0ffa3105997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>df4a5a6a-57a7-4b91-865e-d7bb7add7e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'loginUsername' and @name = 'identifier' and @type = 'text' and @placeholder = 'Masukkan username/email Agan']</value>
      <webElementGuid>761906e6-a4a9-4ffe-ba2c-8adfe5e3dcea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
