<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Komunitas Populer_icon_icon__yxYJh h-5 w-_059cf0</name>
   <tag></tag>
   <elementGuidId>c49e783c-0fe4-498d-9a55-7155c3ddd141</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/div/div/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Cari disini&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1cc37e37-3c85-42bf-89d4-a73995f7f35e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon_icon__yxYJh h-5 w-5 text-base fa fa-search text-secondary dark:text-secondary-night</value>
      <webElementGuid>d46746ab-7b77-4598-864d-2cbc40ad1855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sticky left-0 top-0 z-50 w-full border-b border-grey-2 bg-white dark:border-grey-6 dark:bg-grey-7&quot;]/div[@class=&quot;mx-auto flex w-full justify-between px-4 pb-2 pt-2 xl:max-w-7xl&quot;]/div[@class=&quot;ml-2 flex flex-grow items-center justify-end&quot;]/div[@class=&quot;relative z-10 max-w-xl flex-1&quot;]/div[@class=&quot;relative mx-auto h-9 z-10 flex-shrink-0 flex-grow&quot;]/button[@class=&quot;absolute right-0 top-1/2 -translate-y-1/2 px-3 py-3 hover:opacity-75&quot;]/i[@class=&quot;icon_icon__yxYJh h-5 w-5 text-base fa fa-search text-secondary dark:text-secondary-night&quot;]</value>
      <webElementGuid>0ab042e9-6c12-49ec-b5ab-648e975c8c3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div/div/button/i</value>
      <webElementGuid>18b54197-8ee7-4692-9c26-6cb67e27e0a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>891c0169-3b6a-41ef-b0c9-cb9dccaee85c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
